### ISSUE TITLE
Title Error

### ISSUE THREAD

**Issue by lamjed001** [nirewen/discord-netflix#77] opened 2019-04-30 17:02 UTC
![image](https://user-images.githubusercontent.com/23016064/56979561-fbb60f80-6b71-11e9-9987-d92a8c09f7c6.png)

**Comment by NovusTheory** [comment] 2019-04-30 19:24
Duplicate of #69

**Comment by nirewen** [comment] 2019-04-30 19:26
nice

**Closed by nirewen** 2019-04-30 19:26 UTC
