### ISSUE TITLE
Error M7701-1003

### ISSUE THREAD

**Issue by Alteux** [nirewen/discord-netflix#82] opened 2019-06-13 21:52 UTC
Netflix Error M7701-1003
If you experience the error code M7701-1003 on your computer, often accompanied by the following message:

Whoops, something went wrong...
Missing Component
We cannot find all the required components to play Netflix on this device. Please visit chrome://components, locate the WidevineCdm component, and click the "Check for update" button.
It typically points to a component on your browser that needs to be updated or that is being blocked by a security setting or program. Follow the troubleshooting steps below to resolve the issue.

Using MacOS Catalina

**Comment by MJ94** [comment] 2019-06-15 02:32
It looks like this may be a duplicate of issue #63.

**Closed** 2019-06-17 17:27 UTC
Labels: duplicate
